ROBOTSTXT_OBEY = False
LOG_ENABLED = True
LOG_LEVEL = 'DEBUG'
USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36'

CONCURRENT_REQUESTS = 16
DOWNLOAD_DELAY = 3

CONCURRENT_REQUESTS_PER_DOMAIN = 8
CONCURRENT_REQUESTS_PER_IP = 8

SPIDER_MODULES = ['habr']

ITEM_PIPELINES = {
    'pipelines.DataBasePipeline': 300
}